add 02-components
js-tasks-ru/vue-20231109_e-zabrodskaya pull request #3
Opened 2023-11-25 14:37 UTC by Elise1544

2023-11-25 14:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-25 14:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-25 14:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-25 14:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-25 15:06 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-25 18:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-25 19:33 UTC, ShGKme requested changes

2023-11-25 19:33 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/App.js
> +        <CounterButton v-model:count="count" @update:count="count" />
Здесь событие обрабатывается дважды -- один раз явно и один раз в модели

2023-11-25 19:33 UTC, ShGKme commented on 02-components/02-MeetupDescription/components/MeetupDescription.js
> +	template: `<p class="meetup-description">{{description}}</p>`,
У текстовой интерполяции принято добавлять пробелы: `{{ description }}`

2023-11-25 19:33 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <p v-if="this.agendaItem.description">{{this.agendaItem.description}}</p>
В шаблон внедряются свойства экземпляра в область видимости, `this` в нём не пишут

2023-11-25 19:33 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), v-bind(bgImage);
Сейчас свойство `background-image` описано дважды. Это не приводит к ошибкам, так как второе перебивает первое, но всё равно не стоит дублировать одно свойство в CSS с разными значениями.

2023-11-25 19:33 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list :deep(.meetups-list__item).fade-list-move {
Ранее это было универсальный компонент, но теперь он работает, только если в его содержимое передали элементы с классом `meetups-list__item`. Компонент не должен требовать передавать в него содержимое с конкретным классом для работы стилей, здесь они могут работать без этого.

2023-11-26 09:26 UTC, Elise1544 commented on 02-components/01-CounterButtonComponent/App.js
> +        <CounterButton v-model:count="count" @update:count="count" />
Получается, что на всех 3 можно оставить только v-model?

2023-11-26 09:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-26 09:57 UTC, Elise1544 commented on 02-components/02-MeetupDescription/components/MeetupDescription.js
> +	template: `<p class="meetup-description">{{description}}</p>`,
Исправила везде. Привыкла, что на работе автоматом добавляется, а дома не настроено :(

2023-11-26 09:58 UTC, Elise1544 commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <p v-if="this.agendaItem.description">{{this.agendaItem.description}}</p>
Исправила везде.

2023-11-26 10:02 UTC, Elise1544 commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), v-bind(bgImage);
В задании было сказано исправить второе свойство :) Даже не посмотрела на предыдущее. Постараюсь обращать внимание.

2023-11-26 10:06 UTC, Elise1544 commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list :deep(.meetups-list__item).fade-list-move {
Но, логика правильная? Получается, что если указать элемент списка, то это тоже будет требовать именно li, но будет менее специфично?

2023-11-26 15:05 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/App.js
> +        <CounterButton v-model:count="count" @update:count="count" />
`v-model` - это сокращённая запись для двух действий, в данном случае:
```
:count="count"
@update:count="count = $event"
```

С добавлением вашего обработчика события, получается
```
:count="count"
@update:count="count = $event"
@update:count="count"
```

В итоге обработчиков события - два.

2023-11-26 15:06 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/App.js
> +        <CounterButton v-model:count="count" @update:count="count" />
При этом второй обработчик события не имеет смысла. `count` - число. Число не может быть "обработчиком события" и не имеет смысла как выражение.

2023-11-26 15:07 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list :deep(.meetups-list__item).fade-list-move {
Элемент списка тоже будет некорректно. Нет требования, при котором этот компонент может использоваться только с `LI`. В него могут передать и `div`-ы.

2023-11-26 15:10 UTC, ShGKme requested changes

2023-11-26 15:10 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
Такие селекторы всё ещё работают, только если передать в содержимое компонента определённую вёрстку, в данном случае `<li>`. Добавление инкапсуляции стилей не должно ограничивать использование компонента.

2023-11-27 13:31 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-28 00:03 UTC, ShGKme requested changes

2023-11-28 00:03 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
Ранее это правило определяло стиль элемента с классом `.fade-list` в этом компоненте, но теперь он определяет стиль всех элементов внутри этого компонента. В итоге все элементы на любом уровне вложенности теперь имеют стиль `position: relative`. Это правило работает корректно и без deep, так как оно определяет стили элемента в этом компоненте, что корректно работает в scoped стилях.

2023-11-28 00:03 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
Аналогично это правило раньше действовало только на непосредственно дочерние элементы. Но теперь меняет свойство всех потомков.

2023-11-28 00:03 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
`*.className` и `.className` - одно и то же, так как любой элемент с классом и элемент с классом - одно и то же.

2023-11-28 19:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-30 21:55 UTC, ShGKme requested changes

2023-11-30 21:55 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
```
  opacity: 1;
  transition: opacity 0.3s ease-out;
```

Эти стили всё ещё не действуют на дочерние элементы, так как дочерние элементы не попадают под инкапсуляцию. Остальные стили работают корректно.

2023-12-01 06:55 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-01 08:42 UTC, ShGKme approved these changes

2023-12-01 08:44 UTC, merged