add solution for 4 lesson
js-tasks-ru/vue-20231109_e-zabrodskaya pull request #4
Opened 2023-12-04 18:04 UTC by Elise1544

2023-12-04 18:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-08 18:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-08 19:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-09 12:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-09 13:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-09 13:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-10 19:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-10 20:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-11 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-11 20:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-13 01:58 UTC, ShGKme requested changes
Требуются небольшие исправления в `04-vue-cli/02-TheToaster` и `04-vue-cli/03-UiDropdown1` по комментариям, остальные задачи приняты

2023-12-13 01:58 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +			return {top: top};
Можно вернуть любое `falsy` значение, тогда скроллинга не будет, так как его по умолчанию нет.

2023-12-13 01:58 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +      let query = this.$router.currentRoute.value.query.from
Текущий маршрут вместо `this.$router.currentRoute.value` можно достать из `this.$route`

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      return this.options.filter(option => option.icon).length > 0 ? true : false
Здесь хорошо подойдёт метод `some`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>    </div>
Оборачивание в `div` для `v-for` здесь лишнее

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
`this.toast` не является состоянием компонента, его данными, и используется только во время работы этой функции. Этот объект некорректно хранить как данные компонента.

Если в функции нужна переменная, можно использовать обычные JS переменные с `const/let`.

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      <UiIcon :icon="choosenOption ? choosenOption.icon : ''" class="dropdown__icon" />
Иконка экземпляром компонента `UiIcon` здесь выводится всегда, даже когда иконки нет. В результате выводится иконка с некорректным именем `''`, а в консоли можно увидеть ошибки от компонента.

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      <button v-for="option in options" @click="update(modelValue)" class="dropdown__item" :class="{'dropdown__item_icon' : isIcons}" role="option" type="button" :value="option.value">
У полей ввода мы работали с свойством `value`, так именно этим свойством определяется значение поля ввода, и из него же можно получить значение после ввода пользователем. Но кнопке за очень редким исключением не нужно значение. Это не элемент ввода, а значение на ней использовалось только в старые времена, когда у формы было несколько сабмит кнопок, сама форма отправлялась без JS, и нужно было на сервере узнать, какая кнопка была нажата.

2023-12-13 01:58 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      <button v-for="option in options" @click="update(modelValue)" class="dropdown__item" :class="{'dropdown__item_icon' : isIcons}" role="option" type="button" :value="option.value">
Здесь можно в `update` сразу передавать `option`, чтобы знать, какой именно вариант был выбран.

2023-12-18 20:37 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-19 23:05 UTC, ShGKme approved these changes
Принято

2023-12-19 23:05 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +			return {top: top};
Здесь небольшая проблема осталась.

Здесь можно вернуть `false` / `undefined` без вычисления положения. Роутер по умолчанию не меняет положение.

2023-12-19 23:08 UTC, merged